POST https://luninha.onrender.com/register HTTP/1.1
Content-Type: application/json

{
    "name": "Luna",
    "email": "lunapereira921@gmail.com",
    "password": "1234"
}

###

POST https://luninha.onrender.com/login HTTP/1.1
Content-Type: application/json

{
    "email": "lunapereira921@gmail.com",
    "password": "1234"
}
